name: contactor_example
description: "A powerful and fast Flutter plugin designed to fetch contacts directly from the device. It provides a seamless and efficient way to retrieve names and phone numbers, making it ideal for apps that require quick access to a user's contact list."

environment:
  sdk: ^3.6.0-266.0.dev
dependencies:
  flutter:
    sdk: flutter

  contactor:
    path: ../
  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true