name: contactor
description: "A powerful and fast Flutter plugin designed to fetch contacts directly from the device"
version: 1.0.1
author: Mohammed Asif <moh.asif@protonmail.ch>
repository: https://github.com/Asif-Faizal/Contactor
license: MIT
homepage:

environment:
  sdk: ^3.6.0-266.0.dev
  flutter: '>=3.3.0'

dependencies:
  build_runner: ^2.4.12
  flutter:
    sdk: flutter
  mockito: ^5.4.4
  permission_handler: ^11.3.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.contactor
        pluginClass: ContactorPlugin
      ios:
        pluginClass: SwiftContactorPlugin